-- Seed Products
INSERT INTO products (vendorId, name, description, price, category, stock, rating, image, templeName, weightOptions)
SELECT * FROM (
  SELECT 'system' as vId, 'Brass Ganesha Idol' as n, 'Handcrafted pure brass Ganesha idol for your home altar. Intricately detailed with traditional motifs, perfect for daily worship and gifting.' as d, 1250.00 as p, 'Idols' as c, 50 as s, 4.8 as r, 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&q=80&w=400' as i, NULL as t, NULL as w
  UNION ALL SELECT 'system', 'Sandalwood Incense Sticks', 'Premium Mysore sandalwood incense sticks. Each stick burns 45-60 minutes filling your space with a calming, divine aroma ideal for meditation and daily puja.', 150.00, 'Incense', 200, 4.5, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=400', NULL, NULL
  UNION ALL SELECT 'system', 'Rudraksha Mala', 'Original 108+1 beads Panchmukhi Rudraksha mala from Nepal. Energized and blessed as per Vedic rituals — ideal for japa meditation and spiritual protection.', 450.00, 'Mala', 100, 4.9, 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&q=80&w=400', NULL, NULL
  UNION ALL SELECT 'system', 'Bhagavad Gita', 'The Bhagavad Gita As It Is — Deluxe hardbound edition with original Sanskrit shlokas, English transliteration, word-for-word meanings, and commentary.', 599.00, 'Books', 75, 5.0, 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400', NULL, NULL
  UNION ALL SELECT 'system', 'Copper Shri Yantra', 'Geometrically precise energized copper Shri Yantra for prosperity and positive energy. Consecrated as per Vedic rituals.', 850.00, 'Yantras', 30, 4.7, 'https://images.unsplash.com/photo-1590050752117-23a9d7fc6bbd?auto=format&fit=crop&q=80&w=400', NULL, NULL
  UNION ALL SELECT 'system', 'Kashi Vishwanath Prasad', 'Special Ladoo Prasad from Kashi Vishwanath Temple, Varanasi. Freshly prepared by temple priests and dispatched with the blessings of Lord Shiva.', 250.00, 'Prasad', 100, 4.9, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=400', 'Kashi Vishwanath', '[{"label": "250g", "price": 250}, {"label": "500g", "price": 450}]'
  UNION ALL SELECT 'system', 'Tirupati Laddu', 'Authentic Tirupati Balaji Temple Laddu Prasad prepared by temple priests using the original sacred recipe. Carries the divine blessings of Lord Venkateswara.', 350.00, 'Prasad', 50, 5.0, 'https://images.unsplash.com/photo-1606808214785-6ccf20e5b7df?auto=format&fit=crop&q=80&w=400', 'Tirupati Balaji', '[{"label": "1 Unit", "price": 350}, {"label": "2 Units", "price": 650}]'
  UNION ALL SELECT 'system', 'Premium Brass Diya', 'Handcrafted brass diya with intricate engravings. Perfect for daily puja, Diwali celebrations, and auspicious occasions. Comes with a cotton wick.', 499.00, 'Puja Essentials', 50, 4.8, 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&q=80&w=400', NULL, NULL
  UNION ALL SELECT 'system', 'Puja Samagri Kit', 'Complete puja samagri kit with all essentials — kumkum, haldi, chandan, camphor, dhoop, supari, paan, and more. Everything you need for a complete puja in one box.', 349.00, 'Samagri Kits', 80, 4.6, 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=400', NULL, NULL
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM products LIMIT 1);

-- Seed Pujas
INSERT INTO pujas (vendorId, title, description, onlinePrice, offlinePrice, duration, samagriList)
SELECT * FROM (
  SELECT 'system' as vId, 'Ganesh Puja' as t, 'Invoke the blessings of Lord Ganesha for new beginnings and removing obstacles.' as d, 1100.00 as op, 2100.00 as ofp, '1.5 Hours' as dur, 'Ganesha Idol, Turmeric, Kumkum, Sandalwood Paste, Incense Sticks, Lamp, Flowers, Fruits, Betel Leaves, Betel Nuts, Coconut, Rice, Sweets (Modak).' as sl
  UNION ALL SELECT 'system', 'Satyanarayan Katha', 'A sacred ritual dedicated to Lord Vishnu for peace, prosperity, and happiness.', 2500.00, 5100.00, '3 Hours', 'Satyanarayan Photo, Panchamrit (Milk, Curd, Ghee, Honey, Sugar), Banana Leaves, Flowers, Fruits, Tulsi Leaves, Kalash, Mango Leaves, Wheat, Ghee for Havan, Samidha Sticks.'
  UNION ALL SELECT 'system', 'Lakshmi Puja', 'Attract wealth and prosperity with this special puja dedicated to Goddess Lakshmi.', 1800.00, 3500.00, '2 Hours', 'Lakshmi Idol/Photo, Silver/Gold Coins, Lotus Flowers, Red Cloth, Rice, Turmeric, Kumkum, Sandalwood, Incense, Lamp, Ghee, Fruits, Sweets, Betel Leaves, Nuts.'
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM pujas LIMIT 1);
